"""add progress_measurements

Revision ID: cd7e538bd9b8
Revises: fa4187d3880f
Create Date: 2026-08-02 14:53:50.224849

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cd7e538bd9b8'
down_revision: str | Sequence[str] | None = 'fa4187d3880f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_measurements',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('therapist_id', sa.UUID(), nullable=True),
    sa.Column('treatment_session_id', sa.UUID(), nullable=True),
    sa.Column('assessment_type', sa.String(length=20), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pain_score', sa.Integer(), nullable=True),
    sa.Column('rom_degrees', sa.Integer(), nullable=True),
    sa.Column('strength_scale', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('pain_score BETWEEN 0 AND 10', name='chk_progress_measurements_pain_score'),
    sa.CheckConstraint('rom_degrees BETWEEN 0 AND 360', name='chk_progress_measurements_rom_degrees'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['treatment_session_id'], ['treatment_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_measurements_assessment_type'), 'progress_measurements', ['assessment_type'], unique=False)
    op.create_index(op.f('ix_progress_measurements_measured_at'), 'progress_measurements', ['measured_at'], unique=False)
    op.create_index(op.f('ix_progress_measurements_patient_id'), 'progress_measurements', ['patient_id'], unique=False)
    op.create_index('ix_progress_measurements_patient_timestamp', 'progress_measurements', ['patient_id', 'measured_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_progress_measurements_patient_timestamp', table_name='progress_measurements')
    op.drop_index(op.f('ix_progress_measurements_patient_id'), table_name='progress_measurements')
    op.drop_index(op.f('ix_progress_measurements_measured_at'), table_name='progress_measurements')
    op.drop_index(op.f('ix_progress_measurements_assessment_type'), table_name='progress_measurements')
    op.drop_table('progress_measurements')
    # ### end Alembic commands ###
